### PR TITLE
[Style] Adopt eslint-config-xo-space/esnext

### LINKED ISSUE #27: [Style] Consider using ESlint instead of jshint
[ESlint](http://eslint.org/) is more common these days and has more active development. In addition, there are several widely used eslint configs, and you can easily add your own per-project preferences on top of these configs.

- [eslint-config-xo](https://github.com/sindresorhus/eslint-config-xo) - My personal favorite (I specifically use the `xo/esnext` variant for ES6), also available in a variant that uses [2 spaces instead of tabs](https://github.com/sindresorhus/eslint-config-xo-space)
- [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) - Airbnb's config
- [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) - Enforces JavaScript [Standard](https://standardjs.com/) style
- [eslint-config-eslint](https://www.npmjs.com/package/eslint-config-eslint) - The default eslint config
- [eslint-config-google](https://www.npmjs.com/package/eslint-config-google) - Google's config

Let me know if any of these seem good to you, and I'll open a PR to implement it.

### PR DESCRIPTION
**Pull request by Lange**
This PR gets rid of jshint and implements ESlint (with the `xo-space/esnext` config) in its place.

I did have to make one modification to the config to disable the `new-cap` rule. Normally I'd keep that rule, but given the way that `obs-websocket`'s calls are named I think it makes sense for us to use the exact same method and event names here.

This PR also adds a rudimentary `npm test` command which simply runs static analysis via ESlint. It's a start!

Closes #27.

### CODE REVIEW

**Comment by haganbmj** [comment]
Looks good to me. Not opposed to differing from the plugin's naming convention if it makes consumer code cleaner, though.

**Comment by Lange** [comment]
For now, I think it's okay to stick with the plugin's exact naming convention. If we find that this isn't optimal for whatever reason, we can change it.

**Comment by Lange** [comment]
Though, that said, everyone who uses this library and also has an eslint config with `new-cap` will get linter warnings on every method call, which _will_ get annoying. That might be enough reason to go ahead and switch over to `camelCase` for the method names.

**Comment by haganbmj** [comment]
Either switching to `.requestName` or `.sendRequestName` or something similar.

**Comment by haganbmj** [comment]
Yeah, seems better to just differ a bit than impose bad style.

**Comment by Lange** [comment]
For compatibility's sake, I'll probably make both `UpperCamelCase` and `lowerCamelCase` versions available -- it doesn't really hurt anything or cost any extra resources to do so, and it's only one or two extra lines of code. I'd also update the README to encourage the use of the `lowerCamelCase` variants.

Sound good? If so, I'll add that to this PR.

**Comment by haganbmj** [comment]
Yeah that sounds like a reasonable solution. Appreciate it.

**Comment by Lange** [comment]
Should be good to merge now.

I also changed the `MethodBinding` lib to be `methodBinding`, and I refactored the `AuthHashing` lib to return a proper `class`.

**Comment by haganbmj** [comment]
Awesome thanks for adjusting that.

**Pull request merged**
